// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1DSWPsO8kBvw7xYDP-Cp2BkiUEsez-5w',
    appId: '1:387571810086:web:a5e60c4982703b7f668be7',
    messagingSenderId: '387571810086',
    projectId: 'antamapp-d3015',
    authDomain: 'antamapp-d3015.firebaseapp.com',
    storageBucket: 'antamapp-d3015.firebasestorage.app',
    measurementId: 'G-ZN5EMJCX00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR0bD67Uq4eqmvxcOAD__2VCnTh_FOxWY',
    appId: '1:387571810086:android:42f3a213d312af23668be7',
    messagingSenderId: '387571810086',
    projectId: 'antamapp-d3015',
    storageBucket: 'antamapp-d3015.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd_8VNwXd-pTNakGmKO4tMk-4PKWXzfSg',
    appId: '1:387571810086:ios:681c698642729d05668be7',
    messagingSenderId: '387571810086',
    projectId: 'antamapp-d3015',
    storageBucket: 'antamapp-d3015.firebasestorage.app',
    iosBundleId: 'com.example.antamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd_8VNwXd-pTNakGmKO4tMk-4PKWXzfSg',
    appId: '1:387571810086:ios:681c698642729d05668be7',
    messagingSenderId: '387571810086',
    projectId: 'antamapp-d3015',
    storageBucket: 'antamapp-d3015.firebasestorage.app',
    iosBundleId: 'com.example.antamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1DSWPsO8kBvw7xYDP-Cp2BkiUEsez-5w',
    appId: '1:387571810086:web:8d78521a17175a81668be7',
    messagingSenderId: '387571810086',
    projectId: 'antamapp-d3015',
    authDomain: 'antamapp-d3015.firebaseapp.com',
    storageBucket: 'antamapp-d3015.firebasestorage.app',
    measurementId: 'G-78NWMJ7E7J',
  );

}
